---
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Template preparation

## Reagents required

* lysis buffer (Made in-house, see recipe below)
* proteinase K (20mg/ml)
* thermomixer
* 1.5ml eppendorf tubes   

<div class="panel panel-default">
<div class="panel-heading">
<p class="panel-title">
   
**Lysis buffer (Total vol 50ml)**  

</p>
</div>
<div class="panel-body>

|volume ($\mu$l)|stock Reagent|conccentration in lysis buffer|
|:----:|:----:|:----|
|2500 |1M KCl|50mM KCl|
|500 |1M Tris (pH 8.3)|10mM Tris (pH 8.3)|
|125 |1M MgCl~2~|2.5mM MgCl~2~|
|225 |Nonidet p-40|0.45% Nonidet p-40|
|225 |Tween-20|0.45% Tween-20|
|250 |2% gelatin|0.01% gelatin|

</div>
<div class="panel-footer">

Make-up to 50ml with mol grade water. Autoclave, aliquot and store at -20  

</div>
</div>


## Protocol 

1. UV plastic ware and mol grade water for 15min
2. Transfer 1000 ethanol-fixed L3s (or L1s or eggs) to 1.5ml tube
3. Add lysis buffer to achieve a vol 1.4ml and incubate at room temp for 5min
4. Centrifuge at 13000g for 4min to pellet parasite material
5. Remove and discard majority of supernatent (do not touch pellet)
6. Add 1ml lysis buffer and re-suspend pellet with pipet
7. Repeat steps 4-6 twice more
8. Centrifugeat 13000g for 4min to pellet parasite material
9. Remove and discard supernatent to leave approx 100$\mu$l
10. Re-suspend pellet and add another 50$\mu$l of lysis buffer

11. If lysing L3s place on thermomixer for 15min at 95 with shaking (1000RPM)  
*This helps with the break down of the L3s tough outer sheath*

12. Place at -80 for a min of 1hour to allow ice crystals to help with the degradation process
13. Allow to de-frost on ice
14. Add 6$\mu$l Proteniase K (20mg/ml) to each sample to achieve a final conc of 0.8mg/ml in 150$\mu$l
15. Place on thermomixer at 55 for 120min with shaking at 800RPM followed by 20min at 95 to denature the proteinase K
16. Place directly on ice and make a 1:10 lysate dilution (with mol grade water) in a new tube for using as template for PCR 
17. Store both lysate and lysate dilution at -80  
*Storage at -80 is critical due to the crude nature of the DNA preparation as quality of template will degrade over time at -20*

