---
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Library preparation

## Amplication of ITS-2 region 

### Reagents required

* Kapa HiFi Hotstart PCR kit with dNTPs (Kapa Biosystems, KK2502)
* 0.2ml 96-well plates, clear, half-skirted (VWR, 83007-374)
* Microseal "A" film (Biorad, MSA-5001)
* 1.5ml tubes
* 8-channel pipettor
* filter aerosol tips
* mol grade water
* thermocycler

### Forward Primers

|Name|Sequence|
|:----:|:----:|
|NC1_with_Illumina_Adapter_(0N)|TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGACGTCTGGTTCAGGGTTGTT|
|NC1_with_Illumina_Adapter_(1N)|TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGNACGTCTGGTTCAGGGTTGTT|
|NC1_with_Illumina_Adapter_(2N)|TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGNNACGTCTGGTTCAGGGTTGTT|
|NC1_with_Illumina_Adapter_(3N)|TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGNNNACGTCTGGTTCAGGGTTGTT|


### Reverse primers

|Name|Sequence|
|:----:|:----:|
|NC2_with_Illumina_Adapter_(0N)|GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTAGTTTCTTTTCCTCCGCT|
|NC2_with_Illumina_Adapter_(1N)|GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGNTTAGTTTCTTTTCCTCCGCT|
|NC2_with_Illumina_Adapter_(2N)|GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGNNTTAGTTTCTTTTCCTCCGCT|
|NC2_with_Illumina_Adapter_(3N)|GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGNNNTTAGTTTCTTTTCCTCCGCT|

### Protocol

1. UV pasticware and mol grade water for 15min prior to PCR set-up
2. Combine 2.5$\mu$l of each of the forward primers at stock concentration (100nM) to 90$\mu$l of mol grade water to achieve forward primer mix at 10nM working concentrationOn. Do the same for the reverse primers.
3. On ice make-up Mastermix using forward and reverse primer mixes and the recipe below.
4. Aliquot mastermix (21$\mu$l) to each well of 96-well plate
5. Add 4$\mu$l template (lysate dilution) to wells using multi-channel pipettor
6. Place microseal "A" film over completed plate and place on thermocycler (with pre-heated lid) and run the program below.  

<div class="panel panel-default">
<div class="panel-heading">

**Mastermix (25$\mu$l)** 

</div>

|volume ($\mu$l)|Reagent|
|:----:|:-----|
|5     |KAPA HiFi Buffer (x5)|
|0.75  |NC1 primer mix (10mM)|
|0.75  |NC2 primer mix (10mM)|
|0.75  |dNTPs (10mM)         |
|0.5   |KAPA HiFi Polymerase (0.5U)|
|13.25 |mol grade water|
|4     |1:10 dilution of lysate| 

</div>
   

**Cycling conditions**  

1. 95 for 2min  
2. 98 for 20sec  
3. 62 for 15sec  
4. 72 for 15sec  
5. Repeat steps 2-4 25 times
6. 72 for 2min  

<div class="panel panel-warning">
<div class="panel-heading">Caution</div>
<div class="panel-body">

*Cycles kept low to limit potential bias, but can be increased to 30-35 cycles for samples with low DNA. If amplicons are not to be cleaned immediately store at -20. It is not advisable though to delay the library preparation process as PCR products will degrade even at -20 if stored for longer than a couple of days*

</div>
</div>

## Magnetic bead purification  

### Reagents required
* AMPure XP beads (Beckman Coulter, A63881) - Aliquot and store at 4degrees
* 96-well Magnetic-Ring stand (Applied biosystems, AM10050)
* 0.8ml 96-well storage plates (Thermo-Scientific, AB-0859)
* 0.2ml 96-well plate, clear, half-skirted (VWR, 83007-374)
* 8-channel pipettors
* Reagent reservoirs
* abosolte ethanol (mol grade)  
* mol grade water  

<div class="panel panel-info">
<div class="panel-heading">Note</div>
<div class="panel-body">

*Filter aerosol pipette tipss and 8-channel pipettor used for majority of steps in this protocol. Also all quantities quoted are for clean-up of a full plate (96 samples)*  

</div>
</div>

### Protocol
1. Bring an aliquot of AMPure beads to room temp  
2. Prepare fresh 80% ethanol from mol grade absolute ethanol (50ml)   
3. Centrifuge amplification plate to collect condensation (300g for 2min)  
4. Remove seal from plate in bio-safety cabinet (if possible)  
5. Transfer the 25$\mu$l reactions into 0.8ml 96-well storage plates using multi-channel pipettor  
6. Voretx beads for 30sec to ensure even disperal before placing in reagent reservoir  
7. Transfer 25$\mu$l of beads to each well of the storage plate and gently pipet up and down 10 times to ensure the beads are well-mixed with the PCR sample  
8. Incubate at room temp for 5min  
9. Place plate on magnetic stand for 2min (or until supernatent has cleared)
10. Once clear use multi-channel pipettor to remove and discard supernatent from the wells  
11. With the plate still on the magnetic stand, wash beads with 80% ethanol by adding 200$\mu$l to each well (using a multi-channel pipettor and a reagent reservoir). Do not re-suspend the beads at this point  
12. Incubate for 30sec (or until clear) and then remove and discard supernatent  
13. Wash again with another 200$\mu$l of 80% ethanol. Incubate for 30sec and then as before remove and discard supernatent.  
14. Use a small volume single-channel pipettor (P20, with fine tips) to remove excess ethanol from each well  
15. Allow beads to air-dry for 15min  
16. Remove plate from magnetic stand  
17. Add 40$\mu$l of mol grade water to each well with multi-channel pipettor and gently pipet up and down 10 times to re-suspend the beads  
18. Incubate at room temp for 2min  
19. Place the plate back on the magnetic stand for 2min (or until cleared)  
20. Transfer approx 34$\mu$l of the supernatent to a new 0.2ml 96-well plate without touching the beads  
21. A microseal "A" is placed over cleaned-up samples to allow temporary storage at -20  

## Addition of Illumina barcodes  

### Reagents required:   
* Kapa HiFi Hotstart PCR kit with dNTPs (Kapa Biosystems, KK2502)
* 0.2ml 96-well plates, clear, half-skirted (VWR, 83007-374)
* Microseal "A" film (Biorad, MSA-5001)
* 1.5ml tubes
* 8-channel pipettor
* filter aerosol tips
* mol grade water
* thermocycler  

### Forward primers

|Primer name|sequence of primer|Row in 96-well plate|  
|:---:|:---|:---:|
|N501_i5| AATGATACGGCGACCACCGAGATCTACACTAGATCGCTCGTCGGCAGCGTC |A| 
|N502_i5| AATGATACGGCGACCACCGAGATCTACACCTCTCTATTCGTCGGCAGCGTC |B| 
|N503_i5| AATGATACGGCGACCACCGAGATCTACACTATCCTCTTCGTCGGCAGCGTC |C|
|N504_i5| AATGATACGGCGACCACCGAGATCTACACAGAGTAGATCGTCGGCAGCGTC |D| 
|N505_i5| AATGATACGGCGACCACCGAGATCTACACGTAAGGAGTCGTCGGCAGCGTC |E| 
|N506_i5| AATGATACGGCGACCACCGAGATCTACACACTGCATATCGTCGGCAGCGTC |F|
|N507_i5| AATGATACGGCGACCACCGAGATCTACACAAGGAGTATCGTCGGCAGCGTC |G| 
|N508_i5| AATGATACGGCGACCACCGAGATCTACACCTAAGCCTTCGTCGGCAGCGTC |H| 

### Reverse primers

|Primer name|sequence of primer|Column in 96-well plate format|  
|:---:|:---|:---:|
|N701_i7| CAAGCAGAAGACGGCATACGAGATTCGCCTTAGTCTCGTGGGCTCGG|1|  
|N702_i7| CAAGCAGAAGACGGCATACGAGATCTAGTACGGTCTCGTGGGCTCGG|2| 
|N703_i7| CAAGCAGAAGACGGCATACGAGATTTCTGCCTGTCTCGTGGGCTCGG|3|  
|N704_i7| CAAGCAGAAGACGGCATACGAGATGCTCAGGAGTCTCGTGGGCTCGG|4|  
|N705_i7| CAAGCAGAAGACGGCATACGAGATAGGAGTCCGTCTCGTGGGCTCGG|5|  
|N706_i7| CAAGCAGAAGACGGCATACGAGATCATGCCTAGTCTCGTGGGCTCGG|6|  
|N707_i7| CAAGCAGAAGACGGCATACGAGATGTAGAGAGGTCTCGTGGGCTCGG|7|  
|N708_i7| CAAGCAGAAGACGGCATACGAGATCCTCTCTGGTCTCGTGGGCTCGG|8|  
|N709_i7| CAAGCAGAAGACGGCATACGAGATAGCGTAGCGTCTCGTGGGCTCGG|9|  
|N710_i7| CAAGCAGAAGACGGCATACGAGATCAGCCTCGGTCTCGTGGGCTCGG|10|  
|N711_i7| CAAGCAGAAGACGGCATACGAGATTGCCTCTTGTCTCGTGGGCTCGG|11|  
|N712_i7| CAAGCAGAAGACGGCATACGAGATTCCTCTACGTCTCGTGGGCTCGG|12|   

### Protocol
1. UV pasticware and mol grade water for 15min prior to PCR set-up
2. On ice make-up Mastermix of water, buffer and dNTPs only (No polymerase or primers yet).
3. Aliquot mastermix (19$\mu$l) to each well of 96-well plate
4. Add 1.25$\mu$l forward primer to each well of the designated row (A-H, see table above).
5. Add 1.25$\mu$l reverse primer to each well of the designated column (1-12, see table above).
5. Add 0.5$\mu$l polyermase to each well
6. Add 3$\mu$l template (amplicons from the 1st round of PCR) to wells using multi-channel pipettor
7. Place microseal "A" film over completed plate and place on thermocycler (with pre-heated lid) and run the program below.
8. The resulting PCR products are cleaned-up using the magnetic bead purification protocol similiar to the 1st round of PCR (see section 3.2 above).

<div class="panel panel-default">
<div class="panel-heading">

**Mastermix (25$\mu$l)**   

</div>

|volume ($\mu$l)|Reagent|
|:----:|:-----|
|5     |KAPA HiFi Buffer (x5)|
|1.25  |Forward primer, N501-508 (10mM)|
|1.25  |Reverse primer, N701-712 (10mM)|
|0.75  |dNTPs (10mM)         |
|0.5   |KAPA HiFi Polymerase (0.5U)|
|13.25 |mol grade water|
|3     |1st round PCR product|    

</div>

**Cycling conditions**  

1. 98 for 45sec  
2. 98 for 20sec  
3. 63 for 20sec  
4. 72 for 2min  
5. Repeat steps 2-4 7 times

<div class="alert alert-warning" role="alert">

Cycles kept low to limit potential bias

</div>

### Individual sample quantification and pooling

1. Nanodrop quantification of cleaned-up products resulting from second round of PCR
2. Make Normalized library by combining samples into a single tube to ensure all samples are present in equal concentrations (typically combine 50ng per sample).This should ensure uniform coverage of reads for all samples in the library.
3. Nanodrop library and dilute with mol grade water to achieve approx 5ng/$\mu$l

