---
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Library Quantification

## Reagents required: 
* Illumina library Quantification Kit, Universal qPCR Mix (Kapa Biosystems, KK4824)
* qPCR machine
* Mol grade water
* 10mM Tris-Hcl, pH 8 with 0.05% Tween-20
* Multiplate PCR plate, low profile, clear, unskirted, (Biorad, MLL9601)
* Microseal "B" seal (Biorad, MSB1001)

<div class="panel panel-info">
<div class="panel-heading">Note</div>
<div class="panel-body">

*When setting-up qPCR reactions always take care when pipetting small volumes and use filter aerosol pipette tips. Work on ice and use foil to prevent UV degradation of sybr green in master mix*

</div>
</div>

## Protocol 

1. Dilute library (1:1000) with 10mM Tris-Hcl, pH 8 with 0.05% Tween-20 in triplicate
2. Using these 1:1000 dilutions set-up 1:2 serial dilutions to achieve 1:2000, 1:4000 and 1:8000 (keep in fridge until needed)
3. Before using the Illumina library Quantification kit for the first time add 1ml of primer premix (x10) to the 5ml bottle of Sybr fast qPCR Master mix (x2) and mix well
4. UV all plasticware and water for 15min
5. Prepare qPCR plate by adding:
     * 12$\mu$l Sybr fast qPCR mastermix (with primers added)  
     * 4$\mu$l mol grade water  
     * and either 4$\mu$l diluted library, one of supplied standards (Standard 1-6) or another 4$\mu$l of mol grade water to act as a negative control
6. Place Microseal "B" seal over raections
6. Run on qPCR machine with the following cycling conditions:
      95 for 5min then 35 cycles of 95 for 30 sec and 60 for 45 sec
7. Look at data to confirm 90-110% reaction efficiency for samples and for standards
8. Calculate library quantification using absolute quantification against the 425bp DNA standard

