---
title: Example Analysis
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
This example will provide you with an example dataset to analyze. You will be able to compare the result obtained from this analysis, and compare it to a previously generated result. This can assess whether you have completed the analysis correctly.

# Download Analysis Files

Go to the download section, and download “Example MiSeq Data Files”. These are the forward and reverse reads generated by an Illumina MiSeq. This dataset contains 26 samples that were obtained from Brazilian cattle farms. Each sample contained 1000 L3 larvae cultured from fecal samples. We will use these files for the example analysis. Typically these files would be downloaded from BaseSpace (Illumina). Also download the example file ```nemabiome.files```. This file contains a list of the samples that we are analyzing, and specifies which files belong to each sample. This is an example of how to construct this particular file. We will use this file for the example analysis, however, typically this file will need to be generated manually prior to the analysis of your samples. 

# Analysis

Follow analysis protocol as described in the ‘Analysis Protocols’ section. (PUT IN LINK?). 

# Example output

You can download the file ```example_nemabiome_results.summary``` file. This is what your output file should look like if you have completed the analysis correctly. You can copy this text into an Excel workbook to better visualize the information. 


