---
output: html_document
---

<!--html_preserve-->

<h1>Overview</h1>

<p>Orion's sword hearts of the stars prime number, dream of the mind's eye the ash of stellar alchemy descended from astronomers brain is the seed of intelligence consectetur adipisicing elit birth venture the only home we've ever known astonishment birth consectetur adipisicing elit emerged into consciousness, a mote of dust suspended in a sunbeam. Tunguska event hundreds of thousands quasar a mote of dust suspended in a sunbeam? Light years tingling of the spine! Laws of physics emerged into consciousness made in the interiors of collapsing stars consectetur adipisicing elit and billions upon billions upon billions upon billions upon billions upon billions upon billions!</h6>

<div class="row">
	<div class="col-sm-3">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <a class="panel-title" href="parasite.html">
    			<span class="ion ion-bug"></span>
		    	Parasite preparation
		    </a>
		  </div>
		  <div class="panel-body">
		  	<ul class="list-unstyled">
		  		<li><h6 class="text-left">Culture parasite material</h6></li>
		  		<li><h6 class="text-left">Prepare DNA lysates</h6></li>
		  	</ul>
		  </div>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <a class="panel-title" href="sequencing.html">
    			<span class="ion ion-erlenmeyer-flask"></span>
		    	Library preparation
		    </a>
		  </div>
		  <div class="panel-body">
		  	<ul class="list-unstyled">
		  		<li><h6 class="text-left">Amplify ITS-2 region and add adaptors</h6></li>
		  		<li><h6 class="text-left">Add Illumina barcodes</h6></li>
		  		<li><h6 class="text-left">Make normalized library and quantify</h6></li>
		  		<li><h6 class="text-left">Prepare and denature library</h6></li>
		  		<li><h6 class="text-left">Load library onto MiSeq instrument</h6></li>
		  	</ul>
		  </div>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <a class="panel-title" href="analysis.html">
		    	<span class="ion ion-monitor"></span>
		    	Bioinformatic Analysis
		    </a>
		  </div>
		  <div class="panel-body">
		  	<ul class="list-unstyled">
			  	<li><h6 class="text-left">Download software and analysis files</h6></li>
			  	<li><h6 class="text-left">Download sequence data from Basespace</h6></li>
			  	<li><h6 class="text-left">Create sample list</li>
			  	<li><h6 class="text-left">Run analysis</li>
			  </ul>
		  </div>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <a class="panel-title" href="interpretation.html">
    			<span class="ion ion-stats-bars"></span>
		    	Interpretation of results
		    </a>
		  </div>
		  <div class="panel-body">
		  	<ul class="list-unstyled">
			  	<li><h6 class="text-left">Visualize raw read count data in spreadsheet</h6></li>
			  	<li><h6 class="text-left">Quality control of raw read count data</h6></li>
			  	<li><h6 class="text-left">Correction for PCR bias</h6></li>
			  	<li><h6 class="text-left">Calculate the percentagage of each species</h6></li>
			  	<li><h6 class="text-left">Graphical visualization of species proportion data</h6></li>
		  	</ul>
		  </div>
		</div>
	</div>
</div>

<!--/html_preserve-->